services:
  netrunner-tutorial:
    container_name: netrunner-tutorial
    image: netrunner-tutorial:latest
    restart: always
    ports:
      - 6701:80
    networks:
      - netrunner

networks:
  netrunner:
    external: true
